version: '3.8'

services:
  social-app:
    container_name: dockerdev
    build:
      dockerfile: Dockerfile-dev
      context: .
    entrypoint: /dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /usr/bin/social
    restart: on-failure
    environment:
      - PGHOST=db
      - PGPORT=5432
      - MIGR_DIR=/usr/bin/migrations
    ports:
      - "8080:8080"
      - "40000:40000"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
