version: '3.8'

services:
  social-app:
    build: .
    entrypoint: /usr/bin/social
    restart: on-failure
    environment:
      - PGHOST=db
      - PGPORT=5432
      - MIGR_DIR=/usr/bin/migrations
    ports:
      - "8080:8080"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
