FROM golang:1.19 AS build-env
WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest
COPY . .

RUN go build -gcflags="all=-N -l" -o ./social ./cmd/app/main.go

FROM debian:buster

EXPOSE 8080 40000

WORKDIR /
COPY --from=build-env /go/bin/dlv /dlv
COPY --from=build-env /app/social /usr/bin/social
COPY --from=build-env /app/internal/migrations /usr/bin/migrations

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/usr/bin/social"]