version: '3.8'

services:
  social-app:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /usr/bin/social
    restart: on-failure
    environment:
      - PGHOST=db
      - PGPORT=5432
      - MIGR_DIR=/usr/bin/migrations
      # можно указать мастера в качестве слэйва если не настроена репликация и не поднимать еще два контейнера с БД
      #- SLAVE_HOST_PORT=db:5432
      - SLAVE_HOST_PORT=slave:5432,asyncslave:5432
      - TARANTOOL_HOST=tarantool
      - TARANTOOL_USER=user
      - TARANTOOL_PASSWORD=password
    ports:
      - "8080:8080"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/master:/var/lib/postgresql/data
  slave:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - /data/pgslave:/var/lib/postgresql/data
  asyncslave:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - /data/pgasyncslave:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  tarantool:
    image: tarantool/tarantool:2.11.0
    restart: always
    environment:
      - TARANTOOL_USER_NAME=user
      - TARANTOOL_USER_PASSWORD=password
    ports:
      - "3301:3301"

volumes:
  db:
    driver: local
  slave:
    driver: local
  asyncslave:
    driver: local
