// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tokenservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValidateTokenClient is the client API for ValidateToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateTokenClient interface {
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type validateTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateTokenClient(cc grpc.ClientConnInterface) ValidateTokenClient {
	return &validateTokenClient{cc}
}

func (c *validateTokenClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/tokens.ValidateToken/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateTokenServer is the server API for ValidateToken service.
// All implementations must embed UnimplementedValidateTokenServer
// for forward compatibility
type ValidateTokenServer interface {
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedValidateTokenServer()
}

// UnimplementedValidateTokenServer must be embedded to have forward compatible implementations.
type UnimplementedValidateTokenServer struct {
}

func (UnimplementedValidateTokenServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedValidateTokenServer) mustEmbedUnimplementedValidateTokenServer() {}

// UnsafeValidateTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateTokenServer will
// result in compilation errors.
type UnsafeValidateTokenServer interface {
	mustEmbedUnimplementedValidateTokenServer()
}

func RegisterValidateTokenServer(s grpc.ServiceRegistrar, srv ValidateTokenServer) {
	s.RegisterService(&ValidateToken_ServiceDesc, srv)
}

func _ValidateToken_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateTokenServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokens.ValidateToken/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateTokenServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidateToken_ServiceDesc is the grpc.ServiceDesc for ValidateToken service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidateToken_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokens.ValidateToken",
	HandlerType: (*ValidateTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _ValidateToken_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/api/userSession.proto",
}
